x-common-env-vars: &common-env-vars
  AIRFLOW__API__BASE_URL: "http://localhost:8080"
  AIRFLOW__API__PORT: 8080
  AIRFLOW__API_AUTH__JWT_SECRET: "astro_c15280"
  AIRFLOW__CORE__AUTH_MANAGER: airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager
  AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
  AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://api-server:8080/execution/"
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__FERNET_KEY: "d6Vefz3G9U_ynXB3cr7y_Ak35tAHkEGAVxuz_B-jzWw="
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@postgres:5432
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@postgres:5432
  AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: True
  AIRFLOW__WEBSERVER__SECRET_KEY: "astro_c15280"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  ASTRONOMER_ENVIRONMENT: local

networks:
  airflow:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  airflow_logs:
    driver: local

services:
  postgres:
    image: docker.io/postgres:12.6
    restart: unless-stopped
    networks:
      - airflow
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db-migration:
    depends_on:
      - postgres
    image: astro_c15280/airflow:latest
    command:
      - airflow
      - db
      - migrate
    networks:
      - airflow
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-db-migration"
    environment: *common-env-vars

  scheduler:
    depends_on:
      - db-migration
    image: astro_c15280/airflow:latest
    command:
      - airflow
      - scheduler
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-scheduler"
    environment: *common-env-vars
    volumes:
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/dags:/usr/local/airflow/dags:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/plugins:/usr/local/airflow/plugins:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/include:/usr/local/airflow/include:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/tests:/usr/local/airflow/tests:z
      
      
      - airflow_logs:/usr/local/airflow/logs
      
    

  dag-processor:
    depends_on:
      - db-migration
    image: astro_c15280/airflow:latest
    command:
      - airflow
      - dag-processor
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-dag-processor"
    environment: *common-env-vars
    volumes:
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/dags:/usr/local/airflow/dags:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/plugins:/usr/local/airflow/plugins:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/include:/usr/local/airflow/include:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/tests:/usr/local/airflow/tests:z
      
      - airflow_logs:/usr/local/airflow/logs
      
    

  api-server:
    depends_on:
      - db-migration
    image: astro_c15280/airflow:latest
    command:
      - airflow
      - api-server
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-api-server"
    environment: *common-env-vars
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/dags:/usr/local/airflow/dags:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/plugins:/usr/local/airflow/plugins:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/include:/usr/local/airflow/include:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/tests:/usr/local/airflow/tests:z
      
      - airflow_logs:/usr/local/airflow/logs
      
    

  triggerer:
    depends_on:
      - db-migration
    image: astro_c15280/airflow:latest
    command:
      - airflow
      - triggerer
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-triggerer"
    environment: *common-env-vars
    volumes:
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/dags:/usr/local/airflow/dags:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/plugins:/usr/local/airflow/plugins:z
      - /home/luludocteur/Documents/GROTTE/TRADING_BOT/Grid_Trading/src/DEC/ASTRO/include:/usr/local/airflow/include:z
      
      - airflow_logs:/usr/local/airflow/logs
      
    
