version: '3.8'

services:
  mariadb:
    
    image: mariadb:latest
    
    container_name: BDD_GridTrading
    
    environment:
      MYSQL_ROOT_PASSWORD: AlexLenul
      MYSQL_DATABASE: DTM_GridTrading
      MYSQL_USER: LeRequeteur
      MYSQL_PASSWORD: LenulAlex
    
    volumes:
      - database:/data/db

    ports:
      - "3306:3306"
volumes:
  database:
