# Use postgres/example user/password credentials

services:

  db:
    image: postgres

    container_name: GTBDD

    volumes:
      - postgresql_GTBDD:/data/db

    environment:
      POSTGRES_PASSWORD: LenulAlex
      POSTGRES_USER: LeRequeteur
      POSTGRES_DB: GTBDD

    ports:
      - "5432:5432"

    networks:
      - astro_c15280_airflow

networks:
  astro_c15280_airflow:
    name: astro_airflow
    external: true
      
volumes:
  postgresql_GTBDD:
